name: Nix CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test_generate:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cachix install
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - name: TestGenerate
      run: |
        cd test-suite
        ./test_generate.sh
